/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	examplecomv1 "github.com/vinay272001/Crd-assignment/pkg/apis/example.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExampleCrds implements ExampleCrdInterface
type FakeExampleCrds struct {
	Fake *FakeExamplecrdV1
	ns   string
}

var examplecrdsResource = schema.GroupVersionResource{Group: "examplecrd.k8s.io", Version: "v1", Resource: "examplecrds"}

var examplecrdsKind = schema.GroupVersionKind{Group: "examplecrd.k8s.io", Version: "v1", Kind: "ExampleCrd"}

// Get takes name of the exampleCrd, and returns the corresponding exampleCrd object, and an error if there is any.
func (c *FakeExampleCrds) Get(ctx context.Context, name string, options v1.GetOptions) (result *examplecomv1.ExampleCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(examplecrdsResource, c.ns, name), &examplecomv1.ExampleCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.ExampleCrd), err
}

// List takes label and field selectors, and returns the list of ExampleCrds that match those selectors.
func (c *FakeExampleCrds) List(ctx context.Context, opts v1.ListOptions) (result *examplecomv1.ExampleCrdList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(examplecrdsResource, examplecrdsKind, c.ns, opts), &examplecomv1.ExampleCrdList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &examplecomv1.ExampleCrdList{ListMeta: obj.(*examplecomv1.ExampleCrdList).ListMeta}
	for _, item := range obj.(*examplecomv1.ExampleCrdList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested exampleCrds.
func (c *FakeExampleCrds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(examplecrdsResource, c.ns, opts))

}

// Create takes the representation of a exampleCrd and creates it.  Returns the server's representation of the exampleCrd, and an error, if there is any.
func (c *FakeExampleCrds) Create(ctx context.Context, exampleCrd *examplecomv1.ExampleCrd, opts v1.CreateOptions) (result *examplecomv1.ExampleCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(examplecrdsResource, c.ns, exampleCrd), &examplecomv1.ExampleCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.ExampleCrd), err
}

// Update takes the representation of a exampleCrd and updates it. Returns the server's representation of the exampleCrd, and an error, if there is any.
func (c *FakeExampleCrds) Update(ctx context.Context, exampleCrd *examplecomv1.ExampleCrd, opts v1.UpdateOptions) (result *examplecomv1.ExampleCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(examplecrdsResource, c.ns, exampleCrd), &examplecomv1.ExampleCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.ExampleCrd), err
}

// Delete takes name of the exampleCrd and deletes it. Returns an error if one occurs.
func (c *FakeExampleCrds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(examplecrdsResource, c.ns, name, opts), &examplecomv1.ExampleCrd{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExampleCrds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(examplecrdsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &examplecomv1.ExampleCrdList{})
	return err
}

// Patch applies the patch and returns the patched exampleCrd.
func (c *FakeExampleCrds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *examplecomv1.ExampleCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(examplecrdsResource, c.ns, name, pt, data, subresources...), &examplecomv1.ExampleCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.ExampleCrd), err
}
