/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/vinay272001/Crd-assignment/pkg/apis/example.com/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ExampleCrdLister helps list ExampleCrds.
// All objects returned here must be treated as read-only.
type ExampleCrdLister interface {
	// List lists all ExampleCrds in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ExampleCrd, err error)
	// ExampleCrds returns an object that can list and get ExampleCrds.
	ExampleCrds(namespace string) ExampleCrdNamespaceLister
	ExampleCrdListerExpansion
}

// exampleCrdLister implements the ExampleCrdLister interface.
type exampleCrdLister struct {
	indexer cache.Indexer
}

// NewExampleCrdLister returns a new ExampleCrdLister.
func NewExampleCrdLister(indexer cache.Indexer) ExampleCrdLister {
	return &exampleCrdLister{indexer: indexer}
}

// List lists all ExampleCrds in the indexer.
func (s *exampleCrdLister) List(selector labels.Selector) (ret []*v1.ExampleCrd, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ExampleCrd))
	})
	return ret, err
}

// ExampleCrds returns an object that can list and get ExampleCrds.
func (s *exampleCrdLister) ExampleCrds(namespace string) ExampleCrdNamespaceLister {
	return exampleCrdNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ExampleCrdNamespaceLister helps list and get ExampleCrds.
// All objects returned here must be treated as read-only.
type ExampleCrdNamespaceLister interface {
	// List lists all ExampleCrds in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ExampleCrd, err error)
	// Get retrieves the ExampleCrd from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ExampleCrd, error)
	ExampleCrdNamespaceListerExpansion
}

// exampleCrdNamespaceLister implements the ExampleCrdNamespaceLister
// interface.
type exampleCrdNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ExampleCrds in the indexer for a given namespace.
func (s exampleCrdNamespaceLister) List(selector labels.Selector) (ret []*v1.ExampleCrd, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ExampleCrd))
	})
	return ret, err
}

// Get retrieves the ExampleCrd from the indexer for a given namespace and name.
func (s exampleCrdNamespaceLister) Get(name string) (*v1.ExampleCrd, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("examplecrd"), name)
	}
	return obj.(*v1.ExampleCrd), nil
}
