/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	examplecomv1 "github.com/vinay272001/Crd-assignment/pkg/apis/example.com/v1"
	versioned "github.com/vinay272001/Crd-assignment/pkg/client/clientset/versioned"
	internalinterfaces "github.com/vinay272001/Crd-assignment/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/vinay272001/Crd-assignment/pkg/client/listers/example.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ExampleCrdInformer provides access to a shared informer and lister for
// ExampleCrds.
type ExampleCrdInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ExampleCrdLister
}

type exampleCrdInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewExampleCrdInformer constructs a new informer for ExampleCrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewExampleCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredExampleCrdInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredExampleCrdInformer constructs a new informer for ExampleCrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredExampleCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExamplecrdV1().ExampleCrds(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExamplecrdV1().ExampleCrds(namespace).Watch(context.TODO(), options)
			},
		},
		&examplecomv1.ExampleCrd{},
		resyncPeriod,
		indexers,
	)
}

func (f *exampleCrdInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredExampleCrdInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *exampleCrdInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&examplecomv1.ExampleCrd{}, f.defaultInformer)
}

func (f *exampleCrdInformer) Lister() v1.ExampleCrdLister {
	return v1.NewExampleCrdLister(f.Informer().GetIndexer())
}
