apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taskruns.phoenix.com
spec:
  group: phoenix.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: 
              message:
                type: string
              count:
                type: integer
  names:
    kind: TaskRun
    listKind: TaskRunList
    plural: taskruns
    singular: taskrun
  scope: Namespaced